import{a as q,i as n,S as v}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function g(o,t=1){const s=new URLSearchParams({key:"51545892-4b8f299c7368d58b68a280d40",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15});try{const{data:a}=await q(`https://pixabay.com/api/?${s}`);return a}catch{n.warning({message:"Помилка відповіді від сервера"})}}const P=new v(".gallery a"),d=document.querySelector(".gallery"),m=document.querySelector(".loader"),f=document.querySelector(".load-more");function h(o){const t=o.map(({largeImageURL:s,webformatURL:a,tags:e,likes:r,views:i,comments:w,downloads:S})=>`
      <li class="galleryblock">
      <a href="${s}">
      <img src="${a}" alt="${e}"></a>
     <ul class="gallery-info">
          <li>Likes<br><strong>${r}</strong></li>
          <li>Views<br><strong>${i}</strong></li>
          <li>Comments<br><strong>${w}</strong></li>
          <li>Downloads<br><strong>${S}</strong></li>
        </ul></li>  `).join("");d.insertAdjacentHTML("beforeend",t),P.refresh()}function y(){m.classList.remove("is-hidden")}function p(){m.classList.add("is-hidden")}function $(){d&&(d.innerHTML="")}function B(){f.classList.remove("is-hidden")}function L(){f.classList.add("is-hidden")}const x=document.querySelector(".form");let c=1,l="",u=15,b=0;x.addEventListener("submit",async o=>{if(o.preventDefault(),L(),l=o.target.elements["search-text"].value.trim(),!l){n.warning({message:"Заповніть пусте поле"});return}$(),y();try{const t=await g(l);if(t.hits.length===0){n.warning({message:"Sorry, there are no images matching your search query. Please try again!"});return}b=Math.ceil(t.totalHits/u),h(t.hits),t.totalHits>u?B():n.warning({message:"We are sorry, but you've reached the end of search results"})}catch{n.warning({message:"Помилка відповіді від сервера"})}finally{p()}});const M=document.querySelector(".load-more");M.addEventListener("click",async()=>{c++,y();try{const o=await g(l,c);h(o.hits);let t=document.querySelector(".galleryblock"),{height:s}=t.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"}),b===c&&(L(),n.warning({message:"We are sorry, but you've reached the end of search results"}))}catch{n.warning({message:"Помилка відповіді від сервера"})}finally{p()}});
//# sourceMappingURL=index.js.map
